spring:
  application:
    name: course-catalog-service
message: Hello from default profile

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#message: Hello from prod profile

---
spring:
  config:
    activate:
      on-profile: non-prod
message: Hello from non-prod profile