spring:
  application:
    name: course-catalog-service
  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
    url: jdbc:postgresql://localhost:5438/courses
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
#    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: false

message: Hello from default profile

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#message: Hello from prod profile

---
spring:
  config:
    activate:
      on-profile: non-prod
message: Hello from non-prod profile